# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  testConfiguration: 'Release'
  test_catalog: $(db_catalog)_test

stages:
- stage: Build_And_Unit_Test
  variables:
    dacpacLocation: 'src\database\VideoDB\bin\$(buildConfiguration)\VideoDB.dacpac'
  jobs:
  - job: WebApi
    variables:
      solution: 'src\Watcher.sln'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: $(solution)
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: 'src\test\**\*.csproj'
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: 'src\test\**\*.csproj'
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: 'src\main\**\Watcher.csproj'
        arguments: '-c $(buildConfiguration)'    
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        projects: 'src\main\**\Watcher.csproj'
        arguments: '-c $(buildConfiguration)'    
  