# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  testConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_And_Unit_Test
  variables:
    System.Debug: true
  jobs:
  - job: Watcher
    variables:
      solution: 'src/Watcher.sln'
    steps:
    - powershell: Get-ChildItem -Recurse
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: $(solution)
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: 'src/test/**/*.csproj'
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: 'src/test/**/*.csproj'
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: 'src/main/**/Watcher.csproj'
        arguments: '-c $(buildConfiguration)'    
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        projects: 'src/main/**/Watcher.csproj'
        arguments: '-c $(buildConfiguration)'    
    - publish: 'src/main/Watcher/bin/$(buildConfiguration)/netcoreapp3.0/publish.zip'
      artifact: Watcher
- stage: Deploy
  dependsOn: Build_And_Unit_Test
  jobs:
  - job: Docker
    steps:
    - download: current
      artifact: Watcher
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: $(dockerRegistry)
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: trixter1394/Watcher
        tags: latest
        dockerfile: ./Dockerfile
    - task: Docker@2
      inputs:
        command: logout
